name: test
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
      - run: just test
